import React, { useCallback, useRef } from 'react';
import { View, StyleSheet, FlatList, Dimensions, ActivityIndicator, RefreshControl, TouchableOpacity } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useTranslation } from 'react-i18next';

import { Text } from '@/components/atoms';
import { LanguageToggle } from '@/components/molecules/LanguageToggle';
import StoryTile from '@/components/molecules/StoryTile';
import { goldenTempleTheme } from '@/styles/goldenTempleTheme';
import { useI18nStore } from '@/shared/stores/i18nStore';
import { useTabBarHeight } from '@/hooks/useTabBarHeight';
import { useScrollToTopOnTabPress } from '@/hooks/useScrollToTopOnTabPress';
import { useStoriesList, isStorySeries } from '@/features/feed/hooks/useStories';
import { openAudioPlayer } from '@/utils/openAudioPlayer';
import { Feed } from '@/types/feed';

const { width } = Dimensions.get('window');
// 2 columns: the list's paddingHorizontal (spacing.lg = 24) on each side plus
// a 16px gap between the tiles - same arithmetic as horoscope.tsx's grid.
const TILE_WIDTH = (width - 64) / 2;

/**
 * The Stories tab (Bhav_Bhakti_Stories_Plan.md, phase 4): every series and
 * one-off story as a tile. A series opens story-series.tsx; a one-off story
 * plays straight away. Episodes never appear here - the API only returns
 * them for ?seriesId=.
 */
export default function StoriesScreen() {
  const { t } = useTranslation();
  const { language } = useI18nStore();
  const { contentPadding } = useTabBarHeight();
  const listRef = useRef<FlatList<Feed>>(null);

  const { stories, isLoading, isError, refetch, isRefetching, fetchNextPage, hasNextPage, isFetchingNextPage } =
    useStoriesList();

  useScrollToTopOnTabPress(
    useCallback(() => {
      listRef.current?.scrollToOffset({ offset: 0, animated: true });
    }, [])
  );

  const handlePress = useCallback(
    (feed: Feed) => {
      if (isStorySeries(feed)) {
        // Cast: typed routes are generated by Metro (.expo/types, not in
        // git), so a newly added screen isn't in them until the next start.
        router.push({ pathname: '/(main)/story-series' as any, params: { seriesId: String(feed.id) } });
        return;
      }
      openAudioPlayer({ feed, language, returnTo: '/(main)/stories' });
    },
    [language]
  );

  const handleEndReached = useCallback(() => {
    if (hasNextPage && !isFetchingNextPage) fetchNextPage();
  }, [hasNextPage, isFetchingNextPage, fetchNextPage]);

  const renderEmpty = () => {
    if (isLoading) {
      return (
        <View style={styles.state}>
          <ActivityIndicator size="large" color={goldenTempleTheme.colors.primary.DEFAULT} />
        </View>
      );
    }
    if (isError) {
      return (
        <View style={styles.state}>
          <Ionicons name="cloud-offline-outline" size={40} color={goldenTempleTheme.colors.text.secondary} />
          <Text variant="body" weight="medium" align="center" style={styles.stateTitle}>
            {t('stories.loadError')}
          </Text>
          <TouchableOpacity style={styles.retryButton} onPress={() => refetch()} activeOpacity={0.8}>
            <Text weight="semibold" style={styles.retryText}>
              {t('common.retry')}
            </Text>
          </TouchableOpacity>
        </View>
      );
    }
    return (
      <View style={styles.state}>
        <Ionicons name="book-outline" size={40} color={goldenTempleTheme.colors.text.secondary} />
        <Text variant="body" weight="medium" align="center" style={styles.stateTitle}>
          {t('stories.empty')}
        </Text>
        <Text variant="caption" align="center" style={styles.stateHint}>
          {t('stories.emptyHint')}
        </Text>
      </View>
    );
  };

  return (
    <SafeAreaView style={styles.container} edges={['top']}>
      <View style={styles.header}>
        <Text variant="h4" weight="semibold" style={styles.headerTitle}>
          {t('stories.title')}
        </Text>
        <LanguageToggle />
      </View>

      <FlatList
        ref={listRef}
        data={stories}
        keyExtractor={(item) => String(item.id)}
        renderItem={({ item }) => <StoryTile feed={item} width={TILE_WIDTH} onPress={handlePress} />}
        numColumns={2}
        columnWrapperStyle={styles.row}
        contentContainerStyle={[styles.list, { paddingBottom: contentPadding }]}
        ListEmptyComponent={renderEmpty}
        ListFooterComponent={
          isFetchingNextPage ? (
            <ActivityIndicator style={styles.footer} color={goldenTempleTheme.colors.primary.DEFAULT} />
          ) : null
        }
        onEndReached={handleEndReached}
        onEndReachedThreshold={0.5}
        refreshControl={
          <RefreshControl
            refreshing={isRefetching && !isFetchingNextPage}
            onRefresh={() => refetch()}
            tintColor={goldenTempleTheme.colors.primary.DEFAULT}
            colors={[goldenTempleTheme.colors.primary.DEFAULT]}
          />
        }
        showsVerticalScrollIndicator={false}
      />
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: goldenTempleTheme.colors.background,
  },
  // Same single-row header as the Rashifal grid (title left, language
  // toggle right), minus a back button - this is a tab.
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: goldenTempleTheme.spacing.lg,
    paddingVertical: goldenTempleTheme.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.1)',
  },
  headerTitle: {
    color: goldenTempleTheme.colors.text.primary,
    lineHeight: 32,
    minHeight: 32,
  },
  list: {
    flexGrow: 1,
    paddingHorizontal: goldenTempleTheme.spacing.lg,
    paddingTop: goldenTempleTheme.spacing.lg,
  },
  // flex-start, not space-between: a lone tile on the last row stays in
  // the left column at its normal width.
  row: {
    justifyContent: 'flex-start',
    gap: 16,
  },
  state: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: goldenTempleTheme.spacing.lg,
    paddingVertical: 64,
    gap: goldenTempleTheme.spacing.sm,
  },
  stateTitle: {
    color: goldenTempleTheme.colors.text.primary,
    lineHeight: 24,
  },
  stateHint: {
    color: goldenTempleTheme.colors.text.secondary,
    lineHeight: 18,
  },
  retryButton: {
    marginTop: goldenTempleTheme.spacing.sm,
    paddingHorizontal: goldenTempleTheme.spacing.lg,
    paddingVertical: goldenTempleTheme.spacing.sm,
    borderRadius: 20,
    backgroundColor: goldenTempleTheme.colors.primary.DEFAULT,
  },
  retryText: {
    color: '#fff',
    lineHeight: 22,
    minHeight: 22,
  },
  footer: {
    paddingVertical: goldenTempleTheme.spacing.lg,
  },
});
