import { logAnalyticsEvent } from './logEvent';
import { useRetentionTrackingStore } from '@/store/retentionTrackingStore';
import { getLocalDateString } from '@/shared/utils/dateUtil';

// Retention bucket - see Bhav_Bhakti_Analytics_Event_Plan.md §5. DAU/WAU/MAU
// and full Day 1/7/30 cohort retention curves are NOT built here - they're
// genuinely automatic, generated by Firebase from the session_start event,
// which fires with zero setup the moment the SDK is active. app_reopened is
// the one real custom event this bucket needs.

// Two full local calendar dates in, exact day count out - safe regardless of
// timezone/DST, since both YYYY-MM-DD strings parse to UTC midnight the same
// way, so the offset cancels out in the subtraction.
function daysBetweenDateStrings(earlier: string, later: string): number {
  const ms = new Date(later).getTime() - new Date(earlier).getTime();
  return Math.round(ms / (1000 * 60 * 60 * 24));
}

// Called once per cold start (app/_layout.tsx). Arms a pending app_reopened
// check when the last recorded session was on a strictly earlier local
// calendar date than today - "meaningful gap" is defined as at least 1 full
// calendar day; a same-day reopen (closed and reopened later today) doesn't
// count. This threshold isn't specified by the plan - a deliberate,
// defensible judgment call, not an inferred requirement.
export function recordSessionStartForRetention(): void {
  const today = getLocalDateString();
  const { lastSessionDateString, setLastSessionDateString, setPendingReopenDays } =
    useRetentionTrackingStore.getState();

  if (lastSessionDateString && lastSessionDateString !== today) {
    const days = daysBetweenDateStrings(lastSessionDateString, today);
    if (days >= 1) {
      setPendingReopenDays(days);
    }
  }

  setLastSessionDateString(today);
}

// Consumed by whichever real signal fires first after a qualifying cold
// start, capturing the ACTUAL destination rather than a Rashifal-only yes/no
// - this still lets Rashifal's specific role be analyzed later (by filtering
// this parameter for 'rashifal'), without discarding what everyone else's
// first action actually was:
// - a bottom-nav tab press for mantra/audio/wallpapers/rashifal (see
//   app/(main)/_layout.tsx) -> resolves with that tab's own name. Symmetric
//   across all four - the tab press itself IS "the actual, specific first
//   thing tapped," with no special-casing for any one destination.
// - rashifal_viewed (horoscope-detail.tsx's mount effect) -> resolves
//   'rashifal' too, as a second path covering Home's daily-horoscope card,
//   the one real Rashifal entry point that bypasses the tab bar entirely. If
//   the Rashifal tab itself was pressed first, this call arrives after and
//   is a safe no-op (pendingReopenDays is already null by then).
// - Home is deliberately excluded from resolving anything - it's the
//   automatic landing screen, not a deliberate choice (same reasoning as
//   first_navigation_choice's identical Home exclusion).
//
// Fires ONE complete event only once resolved, rather than firing
// app_reopened immediately at cold start with a placeholder first-action
// value - Firebase events can't be updated after being sent. Real trade-off,
// accepted deliberately: a reopen where the user closes the app again before
// taking any resolving action never gets logged at all, rather than guessing.
export function resolvePendingAppReopened(firstAction: 'rashifal' | 'mantra' | 'audio' | 'wallpapers'): void {
  const { pendingReopenDays, setPendingReopenDays } = useRetentionTrackingStore.getState();
  if (pendingReopenDays === null) return;

  logAnalyticsEvent('app_reopened', {
    days_since_last_session: pendingReopenDays,
    first_action: firstAction,
  });

  setPendingReopenDays(null);
}
